scrape_configs:
  - job_name: "online-cake-shopping-web-app"
    metrics_path: "/api/v1/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets: ["host.docker.internal:8080"] # This is for demo purpose. During  production, change this to the production
