spring:
  application:
    name: back-end

  datasource:
    # url: jdbc:mysql://localhost:3306/crud
    # username: root
    # password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:online-cake-shopping-webapp
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  http:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  servlet:
    multipart:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE
        # INFO

# spring.security:
#   user:
#     name: user # Default user name.
#     password: user # Password
#     roles:    # A comma separated list of roles

server:
  servlet:
    context-path: /api/v1

api:
  endpoint:
    base-url:

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops,heapdump,httpexchanges,loggers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
#    configprops:
#      show-values: always

info:
  app:
    name: online-cake-shopping-webapp
    description: Online Cake Shopping Webapp
    version: "@{project.version}"
    author: Kossei Necira
    links:
      github: https://github.com/kosseinecira
