name: backend-build-test-workflow
# Controls when the workflow will run (workflow triggers)
on:
  push:
    branches: [ main ]
    #paths:
    #  - 'back-end/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
      # Steps represent a sequence of tasks that will be executed as part of the job
      # Download a copy of our repository to ubuntu, allowing us to run actions against our code such us build and test using maven.
      # using actions which is a frequently repeated tasks that reduce the amount of repetitive code.
    steps:
      - uses: actions/checkout@v4
      # Set up JDK for ubuntu runner
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # cache the Maven dependencies to speed up build
          cache: maven
      - name: Build and Test with Maven
        run: mvn --batch-mode package
